<?php

namespace App\Constants;

class Countries
{
    public const LIST = [
        'AD' => ['name' => 'Andorra', 'code' => '+376'],
        'AE' => ['name' => 'United Arab Emirates', 'code' => '+971'],
        'AF' => ['name' => 'Afghanistan', 'code' => '+93'],
        'AG' => ['name' => 'Antigua and Barbuda', 'code' => '+1-268'],
        'AI' => ['name' => 'Anguilla', 'code' => '+1-264'],
        'AL' => ['name' => 'Albania', 'code' => '+355'],
        'AM' => ['name' => 'Armenia', 'code' => '+374'],
        'AO' => ['name' => 'Angola', 'code' => '+244'],
        'AQ' => ['name' => 'Antarctica', 'code' => '+672'],
        'AR' => ['name' => 'Argentina', 'code' => '+54'],
        'AS' => ['name' => 'American Samoa', 'code' => '+1-684'],
        'AT' => ['name' => 'Austria', 'code' => '+43'],
        'AU' => ['name' => 'Australia', 'code' => '+61'],
        'AW' => ['name' => 'Aruba', 'code' => '+297'],
        'AZ' => ['name' => 'Azerbaijan', 'code' => '+994'],
        'BA' => ['name' => 'Bosnia and Herzegovina', 'code' => '+387'],
        'BB' => ['name' => 'Barbados', 'code' => '+1-246'],
        'BD' => ['name' => 'Bangladesh', 'code' => '+880'],
        'BE' => ['name' => 'Belgium', 'code' => '+32'],
        'BF' => ['name' => 'Burkina Faso', 'code' => '+226'],
        'BG' => ['name' => 'Bulgaria', 'code' => '+359'],
        'BH' => ['name' => 'Bahrain', 'code' => '+973'],
        'BI' => ['name' => 'Burundi', 'code' => '+257'],
        'BJ' => ['name' => 'Benin', 'code' => '+229'],
        'BM' => ['name' => 'Bermuda', 'code' => '+1-441'],
        'BN' => ['name' => 'Brunei Darussalam', 'code' => '+673'],
        'BO' => ['name' => 'Bolivia', 'code' => '+591'],
        'BR' => ['name' => 'Brazil', 'code' => '+55'],
        'BS' => ['name' => 'Bahamas', 'code' => '+1-242'],
        'BT' => ['name' => 'Bhutan', 'code' => '+975'],
        'BW' => ['name' => 'Botswana', 'code' => '+267'],
        'BY' => ['name' => 'Belarus', 'code' => '+375'],
        'BZ' => ['name' => 'Belize', 'code' => '+501'],
        'CA' => ['name' => 'Canada', 'code' => '+1'],
        'CD' => ['name' => 'Congo, Democratic Republic of the', 'code' => '+243'],
        'CF' => ['name' => 'Central African Republic', 'code' => '+236'],
        'CG' => ['name' => 'Congo', 'code' => '+242'],
        'CH' => ['name' => 'Switzerland', 'code' => '+41'],
        'CI' => ['name' => 'Côte d`Ivoire', 'code' => '+225'],
        'CL' => ['name' => 'Chile', 'code' => '+56'],
        'CM' => ['name' => 'Cameroon', 'code' => '+237'],
        'CN' => ['name' => 'China', 'code' => '+86'],
        'CO' => ['name' => 'Colombia', 'code' => '+57'],
        'CR' => ['name' => 'Costa Rica', 'code' => '+506'],
        'CU' => ['name' => 'Cuba', 'code' => '+53'],
        'CV' => ['name' => 'Cape Verde', 'code' => '+238'],
        'CY' => ['name' => 'Cyprus', 'code' => '+357'],
        'CZ' => ['name' => 'Czech Republic', 'code' => '+420'],
        'DE' => ['name' => 'Germany', 'code' => '+49'],
        'DJ' => ['name' => 'Djibouti', 'code' => '+253'],
        'DK' => ['name' => 'Denmark', 'code' => '+45'],
        'DM' => ['name' => 'Dominica', 'code' => '+1-767'],
        'DO' => ['name' => 'Dominican Republic', 'code' => '+1-809'],
        'DZ' => ['name' => 'Algeria', 'code' => '+213'],
        'EC' => ['name' => 'Ecuador', 'code' => '+593'],
        'EE' => ['name' => 'Estonia', 'code' => '+372'],
        'EG' => ['name' => 'Egypt', 'code' => '+20'],
        'ER' => ['name' => 'Eritrea', 'code' => '+291'],
        'ES' => ['name' => 'Spain', 'code' => '+34'],
        'ET' => ['name' => 'Ethiopia', 'code' => '+251'],
        'FI' => ['name' => 'Finland', 'code' => '+358'],
        'FJ' => ['name' => 'Fiji', 'code' => '+679'],
        'FR' => ['name' => 'France', 'code' => '+33'],
        'GA' => ['name' => 'Gabon', 'code' => '+241'],
        'GB' => ['name' => 'United Kingdom', 'code' => '+44'],
        'GE' => ['name' => 'Georgia', 'code' => '+995'],
        'GH' => ['name' => 'Ghana', 'code' => '+233'],
        'GM' => ['name' => 'Gambia', 'code' => '+220'],
        'GN' => ['name' => 'Guinea', 'code' => '+224'],
        'GQ' => ['name' => 'Equatorial Guinea', 'code' => '+240'],
        'GR' => ['name' => 'Greece', 'code' => '+30'],
        'GT' => ['name' => 'Guatemala', 'code' => '+502'],
        'GW' => ['name' => 'Guinea-Bissau', 'code' => '+245'],
        'GY' => ['name' => 'Guyana', 'code' => '+592'],
        'HK' => ['name' => 'Hong Kong', 'code' => '+852'],
        'HN' => ['name' => 'Honduras', 'code' => '+504'],
        'HR' => ['name' => 'Croatia', 'code' => '+385'],
        'HT' => ['name' => 'Haiti', 'code' => '+509'],
        'HU' => ['name' => 'Hungary', 'code' => '+36'],
        'ID' => ['name' => 'Indonesia', 'code' => '+62'],
        'IE' => ['name' => 'Ireland', 'code' => '+353'],
        'IL' => ['name' => 'Israel', 'code' => '+972'],
        'IN' => ['name' => 'India', 'code' => '+91'],
        'IQ' => ['name' => 'Iraq', 'code' => '+964'],
        'IR' => ['name' => 'Iran', 'code' => '+98'],
        'IS' => ['name' => 'Iceland', 'code' => '+354'],
        'IT' => ['name' => 'Italy', 'code' => '+39'],
        'JM' => ['name' => 'Jamaica', 'code' => '+1-876'],
        'JO' => ['name' => 'Jordan', 'code' => '+962'],
        'JP' => ['name' => 'Japan', 'code' => '+81'],
        'KE' => ['name' => 'Kenya', 'code' => '+254'],
        'KG' => ['name' => 'Kyrgyzstan', 'code' => '+996'],
        'KH' => ['name' => 'Cambodia', 'code' => '+855'],
        'KI' => ['name' => 'Kiribati', 'code' => '+686'],
        'KM' => ['name' => 'Comoros', 'code' => '+269'],
        'KP' => ['name' => 'Korea, North', 'code' => '+850'],
        'KR' => ['name' => 'South Korea', 'code' => '+82'],
        'KW' => ['name' => 'Kuwait', 'code' => '+965'],
        'KZ' => ['name' => 'Kazakhstan', 'code' => '+7'],
        'LA' => ['name' => 'Lao People`s Democratic Republic', 'code' => '+856'],
        'LB' => ['name' => 'Lebanon', 'code' => '+961'],
        'LI' => ['name' => 'Liechtenstein', 'code' => '+423'],
        'LK' => ['name' => 'Sri Lanka', 'code' => '+94'],
        'LR' => ['name' => 'Liberia', 'code' => '+231'],
        'LS' => ['name' => 'Lesotho', 'code' => '+266'],
        'LT' => ['name' => 'Lithuania', 'code' => '+370'],
        'LU' => ['name' => 'Luxembourg', 'code' => '+352'],
        'LV' => ['name' => 'Latvia', 'code' => '+371'],
        'LY' => ['name' => 'Libya', 'code' => '+218'],
        'MA' => ['name' => 'Morocco', 'code' => '+212'],
        'MC' => ['name' => 'Monaco', 'code' => '+377'],
        'MD' => ['name' => 'Moldova', 'code' => '+373'],
        'ME' => ['name' => 'Montenegro', 'code' => '+382'],
        'MG' => ['name' => 'Madagascar', 'code' => '+261'],
        'MH' => ['name' => 'Marshall Islands', 'code' => '+692'],
        'ML' => ['name' => 'Mali', 'code' => '+223'],
        'MM' => ['name' => 'Myanmar', 'code' => '+95'],
        'MN' => ['name' => 'Mongolia', 'code' => '+976'],
        'MO' => ['name' => 'Macao', 'code' => '+853'],
        'MQ' => ['name' => 'Martinique', 'code' => '+596'],
        'MR' => ['name' => 'Mauritania', 'code' => '+222'],
        'MT' => ['name' => 'Malta', 'code' => '+356'],
        'MU' => ['name' => 'Mauritius', 'code' => '+230'],
        'MV' => ['name' => 'Maldives', 'code' => '+960'],
        'MW' => ['name' => 'Malawi', 'code' => '+265'],
        'MX' => ['name' => 'Mexico', 'code' => '+52'],
        'MY' => ['name' => 'Malaysia', 'code' => '+60'],
        'MZ' => ['name' => 'Mozambique', 'code' => '+258'],
        'NA' => ['name' => 'Namibia', 'code' => '+264'],
        'NE' => ['name' => 'Niger', 'code' => '+227'],
        'NG' => ['name' => 'Nigeria', 'code' => '+234'],
        'NI' => ['name' => 'Nicaragua', 'code' => '+505'],
        'NL' => ['name' => 'Netherlands', 'code' => '+31'],
        'NO' => ['name' => 'Norway', 'code' => '+47'],
        'NP' => ['name' => 'Nepal', 'code' => '+977'],
        'NZ' => ['name' => 'New Zealand', 'code' => '+64'],
        'OM' => ['name' => 'Oman', 'code' => '+968'],
        'PA' => ['name' => 'Panama', 'code' => '+507'],
        'PE' => ['name' => 'Peru', 'code' => '+51'],
        'PG' => ['name' => 'Papua New Guinea', 'code' => '+675'],
        'PH' => ['name' => 'Philippines', 'code' => '+63'],
        'PK' => ['name' => 'Pakistan', 'code' => '+92'],
        'PL' => ['name' => 'Poland', 'code' => '+48'],
        'PS' => ['name' => 'Palestine', 'code' => '+970'],
        'PT' => ['name' => 'Portugal', 'code' => '+351'],
        'PW' => ['name' => 'Palau', 'code' => '+680'],
        'PY' => ['name' => 'Paraguay', 'code' => '+595'],
        'QA' => ['name' => 'Qatar', 'code' => '+974'],
        'RO' => ['name' => 'Romania', 'code' => '+40'],
        'RS' => ['name' => 'Serbia', 'code' => '+381'],
        'RU' => ['name' => 'Russia', 'code' => '+7'],
        'RW' => ['name' => 'Rwanda', 'code' => '+250'],
        'SA' => ['name' => 'Saudi Arabia', 'code' => '+966'],
        'SB' => ['name' => 'Solomon Islands', 'code' => '+677'],
        'SC' => ['name' => 'Seychelles', 'code' => '+248'],
        'SD' => ['name' => 'Sudan', 'code' => '+249'],
        'SE' => ['name' => 'Sweden', 'code' => '+46'],
        'SG' => ['name' => 'Singapore', 'code' => '+65'],
        'SI' => ['name' => 'Slovenia', 'code' => '+386'],
        'SK' => ['name' => 'Slovakia', 'code' => '+421'],
        'SL' => ['name' => 'Sierra Leone', 'code' => '+232'],
        'SN' => ['name' => 'Senegal', 'code' => '+221'],
        'SO' => ['name' => 'Somalia', 'code' => '+252'],
        'SR' => ['name' => 'Suriname', 'code' => '+597'],
        'SV' => ['name' => 'El Salvador', 'code' => '+503'],
        'SY' => ['name' => 'Syria', 'code' => '+963'],
        'TD' => ['name' => 'Chad', 'code' => '+235'],
        'TG' => ['name' => 'Togo', 'code' => '+228'],
        'TH' => ['name' => 'Thailand', 'code' => '+66'],
        'TJ' => ['name' => 'Tajikistan', 'code' => '+992'],
        'TL' => ['name' => 'Timor-Leste', 'code' => '+670'],
        'TM' => ['name' => 'Turkmenistan', 'code' => '+993'],
        'TN' => ['name' => 'Tunisia', 'code' => '+216'],
        'TO' => ['name' => 'Tonga', 'code' => '+676'],
        'TR' => ['name' => 'Turkey', 'code' => '+90'],
        'TT' => ['name' => 'Trinidad and Tobago', 'code' => '+1-868'],
        'TW' => ['name' => 'Taiwan', 'code' => '+886'],
        'TZ' => ['name' => 'Tanzania', 'code' => '+255'],
        'UA' => ['name' => 'Ukraine', 'code' => '+380'],
        'UG' => ['name' => 'Uganda', 'code' => '+256'],
        'US' => ['name' => 'United States', 'code' => '+1'],
        'UY' => ['name' => 'Uruguay', 'code' => '+598'],
        'UZ' => ['name' => 'Uzbekistan', 'code' => '+998'],
        'VE' => ['name' => 'Venezuela', 'code' => '+58'],
        'VN' => ['name' => 'Vietnam', 'code' => '+84'],
        'VU' => ['name' => 'Vanuatu', 'code' => '+678'],
        'YE' => ['name' => 'Yemen', 'code' => '+967'],
        'ZA' => ['name' => 'South Africa', 'code' => '+27'],
        'ZM' => ['name' => 'Zambia', 'code' => '+260'],
        'ZW' => ['name' => 'Zimbabwe', 'code' => '+263'],
    ];
}