export const PAYMENT_STATUS = {
    PAID: 'paid',
    PENDING_PAYMENT: 'pending_payment',
    CANCELLED: 'cancelled',
    REFUNED: 'refuned',
    EXPIRED: 'expired'
};

export const PRESENTATION_TYPE = {
    online_author: 'Online (author/presenter)',
    onsite: 'Onsite',
    participant_only: 'Participant Only'
};

export const PAYMENT_METHOD = {
    transfer_bank: 'Bank Transfer',
    payment_gateway: 'Payment Gateway'
};

export const COUNTRIES = [
  { value: 'AD', label: 'Andorra', code: '+376' },
  { value: 'AE', label: 'United Arab Emirates', code: '+971' },
  { value: 'AF', label: 'Afghanistan', code: '+93' },
  { value: 'AG', label: 'Antigua and Barbuda', code: '+1-268' },
  { value: 'AI', label: 'Anguilla', code: '+1-264' },
  { value: 'AL', label: 'Albania', code: '+355' },
  { value: 'AM', label: 'Armenia', code: '+374' },
  { value: 'AO', label: 'Angola', code: '+244' },
  { value: 'AQ', label: 'Antarctica', code: '+672' },
  { value: 'AR', label: 'Argentina', code: '+54' },
  { value: 'AS', label: 'American Samoa', code: '+1-684' },
  { value: 'AT', label: 'Austria', code: '+43' },
  { value: 'AU', label: 'Australia', code: '+61' },
  { value: 'AW', label: 'Aruba', code: '+297' },
  { value: 'AZ', label: 'Azerbaijan', code: '+994' },
  { value: 'BA', label: 'Bosnia and Herzegovina', code: '+387' },
  { value: 'BB', label: 'Barbados', code: '+1-246' },
  { value: 'BD', label: 'Bangladesh', code: '+880' },
  { value: 'BE', label: 'Belgium', code: '+32' },
  { value: 'BF', label: 'Burkina Faso', code: '+226' },
  { value: 'BG', label: 'Bulgaria', code: '+359' },
  { value: 'BH', label: 'Bahrain', code: '+973' },
  { value: 'BI', label: 'Burundi', code: '+257' },
  { value: 'BJ', label: 'Benin', code: '+229' },
  { value: 'BM', label: 'Bermuda', code: '+1-441' },
  { value: 'BN', label: 'Brunei Darussalam', code: '+673' },
  { value: 'BO', label: 'Bolivia', code: '+591' },
  { value: 'BR', label: 'Brazil', code: '+55' },
  { value: 'BS', label: 'Bahamas', code: '+1-242' },
  { value: 'BT', label: 'Bhutan', code: '+975' },
  { value: 'BW', label: 'Botswana', code: '+267' },
  { value: 'BY', label: 'Belarus', code: '+375' },
  { value: 'BZ', label: 'Belize', code: '+501' },
  { value: 'CA', label: 'Canada', code: '+1' },
  { value: 'CD', label: 'Congo, Democratic Republic of the', code: '+243' },
  { value: 'CF', label: 'Central African Republic', code: '+236' },
  { value: 'CG', label: 'Congo', code: '+242' },
  { value: 'CH', label: 'Switzerland', code: '+41' },
  { value: 'CI', label: 'Côte d`Ivoire', code: '+225' },
  { value: 'CL', label: 'Chile', code: '+56' },
  { value: 'CM', label: 'Cameroon', code: '+237' },
  { value: 'CN', label: 'China', code: '+86' },
  { value: 'CO', label: 'Colombia', code: '+57' },
  { value: 'CR', label: 'Costa Rica', code: '+506' },
  { value: 'CU', label: 'Cuba', code: '+53' },
  { value: 'CV', label: 'Cape Verde', code: '+238' },
  { value: 'CY', label: 'Cyprus', code: '+357' },
  { value: 'CZ', label: 'Czech Republic', code: '+420' },
  { value: 'DE', label: 'Germany', code: '+49' },
  { value: 'DJ', label: 'Djibouti', code: '+253' },
  { value: 'DK', label: 'Denmark', code: '+45' },
  { value: 'DM', label: 'Dominica', code: '+1-767' },
  { value: 'DO', label: 'Dominican Republic', code: '+1-809' },
  { value: 'DZ', label: 'Algeria', code: '+213' },
  { value: 'EC', label: 'Ecuador', code: '+593' },
  { value: 'EE', label: 'Estonia', code: '+372' },
  { value: 'EG', label: 'Egypt', code: '+20' },
  { value: 'ER', label: 'Eritrea', code: '+291' },
  { value: 'ES', label: 'Spain', code: '+34' },
  { value: 'ET', label: 'Ethiopia', code: '+251' },
  { value: 'FI', label: 'Finland', code: '+358' },
  { value: 'FJ', label: 'Fiji', code: '+679' },
  { value: 'FR', label: 'France', code: '+33' },
  { value: 'GA', label: 'Gabon', code: '+241' },
  { value: 'GB', label: 'United Kingdom', code: '+44' },
  { value: 'GE', label: 'Georgia', code: '+995' },
  { value: 'GH', label: 'Ghana', code: '+233' },
  { value: 'GM', label: 'Gambia', code: '+220' },
  { value: 'GN', label: 'Guinea', code: '+224' },
  { value: 'GQ', label: 'Equatorial Guinea', code: '+240' },
  { value: 'GR', label: 'Greece', code: '+30' },
  { value: 'GT', label: 'Guatemala', code: '+502' },
  { value: 'GW', label: 'Guinea-Bissau', code: '+245' },
  { value: 'GY', label: 'Guyana', code: '+592' },
  { value: 'HK', label: 'Hong Kong', code: '+852' },
  { value: 'HN', label: 'Honduras', code: '+504' },
  { value: 'HR', label: 'Croatia', code: '+385' },
  { value: 'HT', label: 'Haiti', code: '+509' },
  { value: 'HU', label: 'Hungary', code: '+36' },
  { value: 'ID', label: 'Indonesia', code: '+62' },
  { value: 'IE', label: 'Ireland', code: '+353' },
  { value: 'IL', label: 'Israel', code: '+972' },
  { value: 'IN', label: 'India', code: '+91' },
  { value: 'IQ', label: 'Iraq', code: '+964' },
  { value: 'IR', label: 'Iran', code: '+98' },
  { value: 'IS', label: 'Iceland', code: '+354' },
  { value: 'IT', label: 'Italy', code: '+39' },
  { value: 'JM', label: 'Jamaica', code: '+1-876' },
  { value: 'JO', label: 'Jordan', code: '+962' },
  { value: 'JP', label: 'Japan', code: '+81' },
  { value: 'KE', label: 'Kenya', code: '+254' },
  { value: 'KG', label: 'Kyrgyzstan', code: '+996' },
  { value: 'KH', label: 'Cambodia', code: '+855' },
  { value: 'KI', label: 'Kiribati', code: '+686' },
  { value: 'KM', label: 'Comoros', code: '+269' },
  { value: 'KP', label: 'Korea, North', code: '+850' },
  { value: 'KR', label: 'South Korea', code: '+82' },
  { value: 'KW', label: 'Kuwait', code: '+965' },
  { value: 'KZ', label: 'Kazakhstan', code: '+7' },
  { value: 'LA', label: 'Lao People`s Democratic Republic', code: '+856' },
  { value: 'LB', label: 'Lebanon', code: '+961' },
  { value: 'LI', label: 'Liechtenstein', code: '+423' },
  { value: 'LK', label: 'Sri Lanka', code: '+94' },
  { value: 'LR', label: 'Liberia', code: '+231' },
  { value: 'LS', label: 'Lesotho', code: '+266' },
  { value: 'LT', label: 'Lithuania', code: '+370' },
  { value: 'LU', label: 'Luxembourg', code: '+352' },
  { value: 'LV', label: 'Latvia', code: '+371' },
  { value: 'LY', label: 'Libya', code: '+218' },
  { value: 'MA', label: 'Morocco', code: '+212' },
  { value: 'MC', label: 'Monaco', code: '+377' },
  { value: 'MD', label: 'Moldova', code: '+373' },
  { value: 'ME', label: 'Montenegro', code: '+382' },
  { value: 'MG', label: 'Madagascar', code: '+261' },
  { value: 'MH', label: 'Marshall Islands', code: '+692' },
  { value: 'ML', label: 'Mali', code: '+223' },
  { value: 'MM', label: 'Myanmar', code: '+95' },
  { value: 'MN', label: 'Mongolia', code: '+976' },
  { value: 'MO', label: 'Macao', code: '+853' },
  { value: 'MQ', label: 'Martinique', code: '+596' },
  { value: 'MR', label: 'Mauritania', code: '+222' },
  { value: 'MT', label: 'Malta', code: '+356' },
  { value: 'MU', label: 'Mauritius', code: '+230' },
  { value: 'MV', label: 'Maldives', code: '+960' },
  { value: 'MW', label: 'Malawi', code: '+265' },
  { value: 'MX', label: 'Mexico', code: '+52' },
  { value: 'MY', label: 'Malaysia', code: '+60' },
  { value: 'MZ', label: 'Mozambique', code: '+258' },
  { value: 'NA', label: 'Namibia', code: '+264' },
  { value: 'NE', label: 'Niger', code: '+227' },
  { value: 'NG', label: 'Nigeria', code: '+234' },
  { value: 'NI', label: 'Nicaragua', code: '+505' },
  { value: 'NL', label: 'Netherlands', code: '+31' },
  { value: 'NO', label: 'Norway', code: '+47' },
  { value: 'NP', label: 'Nepal', code: '+977' },
  { value: 'NZ', label: 'New Zealand', code: '+64' },
  { value: 'OM', label: 'Oman', code: '+968' },
  { value: 'PA', label: 'Panama', code: '+507' },
  { value: 'PE', label: 'Peru', code: '+51' },
  { value: 'PG', label: 'Papua New Guinea', code: '+675' },
  { value: 'PH', label: 'Philippines', code: '+63' },
  { value: 'PK', label: 'Pakistan', code: '+92' },
  { value: 'PL', label: 'Poland', code: '+48' },
  { value: 'PS', label: 'Palestine', code: '+970' },
  { value: 'PT', label: 'Portugal', code: '+351' },
  { value: 'PW', label: 'Palau', code: '+680' },
  { value: 'PY', label: 'Paraguay', code: '+595' },
  { value: 'QA', label: 'Qatar', code: '+974' },
  { value: 'RO', label: 'Romania', code: '+40' },
  { value: 'RS', label: 'Serbia', code: '+381' },
  { value: 'RU', label: 'Russia', code: '+7' },
  { value: 'RW', label: 'Rwanda', code: '+250' },
  { value: 'SA', label: 'Saudi Arabia', code: '+966' },
  { value: 'SB', label: 'Solomon Islands', code: '+677' },
  { value: 'SC', label: 'Seychelles', code: '+248' },
  { value: 'SD', label: 'Sudan', code: '+249' },
  { value: 'SE', label: 'Sweden', code: '+46' },
  { value: 'SG', label: 'Singapore', code: '+65' },
  { value: 'SI', label: 'Slovenia', code: '+386' },
  { value: 'SK', label: 'Slovakia', code: '+421' },
  { value: 'SL', label: 'Sierra Leone', code: '+232' },
  { value: 'SN', label: 'Senegal', code: '+221' },
  { value: 'SO', label: 'Somalia', code: '+252' },
  { value: 'SR', label: 'Suriname', code: '+597' },
  { value: 'SV', label: 'El Salvador', code: '+503' },
  { value: 'SY', label: 'Syria', code: '+963' },
  { value: 'TD', label: 'Chad', code: '+235' },
  { value: 'TG', label: 'Togo', code: '+228' },
  { value: 'TH', label: 'Thailand', code: '+66' },
  { value: 'TJ', label: 'Tajikistan', code: '+992' },
  { value: 'TL', label: 'Timor-Leste', code: '+670' },
  { value: 'TM', label: 'Turkmenistan', code: '+993' },
  { value: 'TN', label: 'Tunisia', code: '+216' },
  { value: 'TO', label: 'Tonga', code: '+676' },
  { value: 'TR', label: 'Turkey', code: '+90' },
  { value: 'TT', label: 'Trinidad and Tobago', code: '+1-868' },
  { value: 'TW', label: 'Taiwan', code: '+886' },
  { value: 'TZ', label: 'Tanzania', code: '+255' },
  { value: 'UA', label: 'Ukraine', code: '+380' },
  { value: 'UG', label: 'Uganda', code: '+256' },
  { value: 'US', label: 'United States', code: '+1' },
  { value: 'UY', label: 'Uruguay', code: '+598' },
  { value: 'UZ', label: 'Uzbekistan', code: '+998' },
  { value: 'VE', label: 'Venezuela', code: '+58' },
  { value: 'VN', label: 'Vietnam', code: '+84' },
  { value: 'VU', label: 'Vanuatu', code: '+678' },
  { value: 'YE', label: 'Yemen', code: '+967' },
  { value: 'ZA', label: 'South Africa', code: '+27' },
  { value: 'ZM', label: 'Zambia', code: '+260' },
  { value: 'ZW', label: 'Zimbabwe', code: '+263' },
];

export const PRESENTATION_TYPES = [
  { value: 'online_author', label: 'Online Author' },
  { value: 'onsite', label: 'Onsite' },
  { value: 'participant_only', label: 'Participant Only' }
];